// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "InsertGuid.6246123a-ffb5-4257-8e09-a5734014e4ac";
        public const string Name = "Insert Guid";
        public const string Description = @"Insert a GUID.Insert a G";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Thomas Sebastian Jensen";
        public const string Tags = "";
    }
}
